<!-- Sidebar 2 - Navigation Panel Component -->
<nav class="sbn" id="sbn">

    <!-- Search box at top - Hidden on desktop (moved to topbar) -->
    <div class="sbn-searchbox d-xl-none">
        <span style="font-size:13px;color:var(--txt4)">
            <i class="fas fa-search"></i>
        </span>
        <input type="text" placeholder="Search">
    </div>

    <div class="sbn-heading">Overview</div>

    <!-- MAIN Section dynamically generated by JS -->
    <div id="sbn-content"></div>

    <!-- Mobile Scroll Hint -->
    <div class="sbn-scroll-hint d-lg-none" id="sbnScrollHint">
        <i class="fas fa-chevron-right"></i>
    </div>

    <!-- Promo Card -->
    <div class="sbn-promo">
        <span class="p-ico">
            <i class="fas fa-mobile-alt" style="font-size: 1.4rem;"></i>
        </span>
        <h6>Get the Mobile App</h6>
        <p>Ask and answer on the go — anywhere, anytime.</p>
        <button>Download</button>
    </div>

</nav>